version: '3.2'

volumes:
  backend:

services:
  api_gateway:
    user: 1000:1000
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - backend_php
    depends_on:
      - backend_php
    volumes:
      - backend:/opt/backend

  backend_php:
    user: 1000:1000
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./backend:/opt/backend
    working_dir: /opt/backend
